### ISSUE TITLE
Question about Auth

### ISSUE THREAD

**Issue by ntorba** [threadhelper/threadhelper#2]
Hello! 

I'm trying to understand how the authentication flow of threadhelper works. I'm a bit confused how I don't need to "sign in with twitter" and it automatically starts working when I got to my twitter page logged in. 

Could you help me understand this? 

I do see the auth description here: https://github.com/threadhelper/threadhelper/blob/254a2b1e00425593ef085e41c14680568353c006/src/README.md, where it says "background.tsx gets auth tokens headers that are scraped from HTTP by functions in auth.jsx." 

I'm curious if you could go into more depth. Which auth method is this? Are there any docs from twitter api on this to reference?

**Comment by steinerkelvin** [comment]
In my understanding, it just extracts the credentials the twitter web app itself is using (what you see at `auth.tsx`) – that's why you don't need to log in – and calls the API in undocumented ways.

**Comment by TheExGenesis** [comment]
That's exactly it, it's a hack needed to work straight out of the box
